name: TestLine

on:
  push:
    branches:
      - main

jobs:
  check-style-help-me:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Build Package
        run: mvn -B clean package -DskipTests

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle